server:
    port: 9191
    servlet:
        context-path: /
#    context-path: /blog-ms-server

spring:
    profiles:
        active: dev
    application:
        name: ms-template-api
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        #    default-property-inclusion: non_null
        time-zone: GMT+8

    #切面设置
#  aop:
#    proxy-target-class: true
#    auto: true
#  cache:
#    type: redis

