spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qpzm@WO849302tgb
#    url: jdbc:mysql://127.0.0.1:3306/myapps?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    url: jdbc:mysql://47.98.202.148:3306/myapps?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true

  jpa:
    show-sql: false

#  redis:
#    #数据库索引
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    lettuce:
#      pool:
#        #最大连接数
#        max-active: 8
#        #最大阻塞等待时间(负数表示没限制)
#        max-wait: -1ms
#        #最大空闲
#        max-idle: 8
#        #最小空闲
#        min-idle: 0
#    #连接超时时间
#    timeout: 10000ms

#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#      enabled: true
#app:
#  base:
#    open-auth: false
#    file-url-host: http://stc.wangjiayang.cn/blog
#    #真实路径
#    upload-path-prefix: /data/stc/blog
#    #临时路径
#    upload-temp-prefix: /data/temp
#    file-path-prefix: /images
#    #文件导入路径
##    file-import: /import
#    #文件导出路径
##    file-export: /export
